### PR TITLE
ADD: CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by daniel-wtd**
- Update: update-meta-files.sh now pulling CODE_OF_CONDUCT.md
- Add: CODE_OF_CONDUCT.md added to docs/ and dist/docs/

Resolves: #14

### CODE REVIEW

**Comment by daniel-wtd** [comment]
Now the meta path is fixed, too.
This "reorg work" is soooo argllll

**Comment by daniel-wtd** [comment]
@Cinux90 maybe you can have a last look? ^^

**Comment by Cinux90** [comment]
Dont know why, but dist/LICENSE show furthermore the content 404... 
And i'm also not sure if dist/LICENSE.j2 needed because LICENSE should be the same in every role...

**Comment by daniel-wtd** [comment]
ahhh, exactly. thats the issue ^^ will change it.

**Comment by daniel-wtd** [comment]
The error should be gone after merging this push.
LICENSE.j2 is renamed to LICENSE, so that the download is working properly.

**Pull request merged**
