### PR TITLE
Fix initial findings 1 2 3

### PR DESCRIPTION
**Pull request by daniel-wtd**
- Update: Readme.md spell check done
- Update: Scripts now using printf blocks instead of echo
- Update: Script output now identical format for tests
- Update: Readme.md Bugs added / workarounds added
- Update: Reorganization to provide better overview
- Rename: .travis.yml now .travis.yml.j2 to be attended from galaxy
- Update: update-meta-files.sh now updating more
- Update: colors added 
- Update: LICENSE date set to 2018
- Update: update-meta-files.sh now including LICENSE

Resolves: #1 #2 #3 

@donvipre  Please review. After this the skeleton should be ok from my side.

### CODE REVIEW

**Comment by daniel-wtd** [comment]
changes applied :)
@donvipre maybe you can have another look.

**Comment by daniel-wtd** [comment]
@donvipre  fixed

**Comment by donvipre** [comment]
@daniel-wtd : now you got on "s" missing ;)

**Comment by daniel-wtd** [comment]
found something else, gimme a sec

**Comment by daniel-wtd** [comment]
@donvipre now with more "s" in the box
@Cinux90 #6 should be addressed, too

**Pull request merged**
